import { useEffect, useState } from 'react';
import {
  API_MODE,
  AUTH_BASE_URL,
  Badge,
  Card,
  Icon,
  toast,
} from '@aip/shared';
import '../styles/dashboard.css';

interface Faq {
  q: string;
  a: string;
}

const FAQS: Faq[] = [
  {
    q: 'How do I log in?',
    a: 'Use the demo accounts shown on the login screen — sunil@demo.com / Demo@123 (candidate) or admin@demo.com / Admin@123 (admin) — or register your own candidate account.',
  },
  {
    q: 'How are my interview questions generated?',
    a: 'Questions are generated by the AI gateway strictly from a curated knowledge base — every question carries citations to the source material it is grounded in. If the knowledge base does not cover your technology well enough, the system refuses to improvise and serves human-reviewed questions from the curated bank instead (you will see a "Curated bank" badge).',
  },
  {
    q: 'Why did the interviewer ask me a follow-up question?',
    a: 'Each question has rubric points generated with it. If your answer misses one, the interviewer probes exactly that point — never invented curiosity. At most one follow-up per question.',
  },
  {
    q: 'How is my interview scored?',
    a: 'Every answer is judged against the same rubric points that were frozen when the question was generated, so all candidates are scored against identical criteria. Your strengths and improvement areas quote the rubric points you covered or missed — evidence, not flattery. Empty or "idk" answers score zero without wasting an evaluation.',
  },
  {
    q: 'What are the camera and tab-switch indicators during the interview?',
    a: 'The camera self-view stays in your browser — video is never uploaded. Switching tabs during an interview increments a proctoring counter that is shown to you in real time; interviews configured with monitoring record it.',
  },
  {
    q: 'Can I change my default interview configuration?',
    a: 'Yes — Settings → Interview Defaults. Those values prefill the Configure Your Interview screen every time.',
  },
  {
    q: 'How long does evaluation take?',
    a: 'Usually under a minute. Evaluation runs asynchronously after you submit; the results page updates itself, and a notification is created when your score is ready.',
  },
];

interface ServiceStatus {
  name: string;
  url: string;
  state: 'checking' | 'up' | 'down';
}

const STATUS_TARGETS: Omit<ServiceStatus, 'state'>[] = [
  { name: 'API Gateway', url: `${AUTH_BASE_URL}/actuator/health` },
  { name: 'Auth', url: 'http://127.0.0.1:8083/actuator/health' },
  { name: 'Interviews', url: 'http://127.0.0.1:8082/actuator/health' },
  { name: 'Notifications', url: 'http://127.0.0.1:8084/actuator/health' },
  { name: 'AI Engine', url: 'http://127.0.0.1:8090/healthz' },
];

export default function HelpPage() {
  const [statuses, setStatuses] = useState<ServiceStatus[]>(
    STATUS_TARGETS.map((t) => ({ ...t, state: 'checking' })),
  );

  useEffect(() => {
    if (API_MODE !== 'real') return;
    let cancelled = false;
    STATUS_TARGETS.forEach(async (target, index) => {
      let state: ServiceStatus['state'] = 'down';
      try {
        const response = await fetch(target.url, { signal: AbortSignal.timeout(4000) });
        state = response.ok ? 'up' : 'down';
      } catch {
        state = 'down';
      }
      if (!cancelled) {
        setStatuses((prev) => prev.map((s, i) => (i === index ? { ...s, state } : s)));
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="page dashboard">
      <header className="dashboard__header">
        <div>
          <h1 className="page__title">Help &amp; Support</h1>
          <p className="page__subtitle">Answers about how the platform works, and whether it is healthy.</p>
        </div>
      </header>

      <div className="help-grid">
        <Card className="help-faq">
          <h2 className="section-title">Frequently Asked Questions</h2>
          {FAQS.map((faq) => (
            <details key={faq.q} className="faq">
              <summary className="faq__question">
                <Icon name="help-circle" size={15} />
                {faq.q}
              </summary>
              <p className="faq__answer">{faq.a}</p>
            </details>
          ))}
        </Card>

        <div className="help-side">
          {API_MODE === 'real' && (
            <Card>
              <h2 className="section-title">System Status</h2>
              <ul className="status-list">
                {statuses.map((s) => (
                  <li key={s.name} className="status-list__row">
                    <span>{s.name}</span>
                    <Badge tone={s.state === 'up' ? 'success' : s.state === 'checking' ? 'neutral' : 'warning'}>
                      {s.state === 'up' ? 'Operational' : s.state === 'checking' ? 'Checking…' : 'Unreachable'}
                    </Badge>
                  </li>
                ))}
              </ul>
            </Card>
          )}

          <Card>
            <h2 className="section-title">Contact Support</h2>
            <p className="adm-muted help-contact-copy">
              Found a bug or need help? Include your interview ID from the results page — it lets us trace
              exactly what happened.
            </p>
            <a className="btn btn--outline btn--block" href="mailto:support@aip.example?subject=AI%20Interview%20Portal%20support">
              <Icon name="mail" size={16} /> support@aip.example
            </a>
            <button
              type="button"
              className="btn btn--ghost btn--block"
              onClick={() => {
                void navigator.clipboard?.writeText(window.location.origin);
                toast('App link copied to clipboard.', 'success');
              }}
            >
              <Icon name="check-circle" size={16} /> Copy app link
            </button>
          </Card>
        </div>
      </div>
    </div>
  );
}
